-- Run this in Supabase SQL Editor after creating a project.
-- Auth identities remain managed by Supabase Auth; profiles hold app-specific roles.

do $$
begin
  create type public.user_role as enum ('Admin', 'District official', 'Field officer', 'Citizen');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.report_status as enum ('Under review', 'Verified', 'Rejected');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  district text,
  role public.user_role not null default 'Citizen',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.field_reports (
  id bigint generated by default as identity primary key,
  submitted_by uuid not null references public.profiles(id),
  location text not null,
  observation text not null,
  severity text not null check (severity in ('Advisory', 'High', 'Critical')),
  status public.report_status not null default 'Under review',
  created_at timestamptz not null default now()
);

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  zone_id text not null,
  severity text not null check (severity in ('Advisory', 'High', 'Critical')),
  status text not null default 'Open' check (status in ('Open', 'Acknowledged', 'Resolved')),
  acknowledged_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data ->> 'full_name', 'Citizen')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.field_reports enable row level security;
alter table public.alerts enable row level security;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile" on public.profiles
  for select using (auth.uid() = id);
drop policy if exists "Authenticated users can read alerts" on public.alerts;
create policy "Authenticated users can read alerts" on public.alerts
  for select to authenticated using (true);
drop policy if exists "Authenticated users can submit reports" on public.field_reports;
create policy "Authenticated users can submit reports" on public.field_reports
  for insert to authenticated with check (auth.uid() = submitted_by);
drop policy if exists "Users can read submitted reports" on public.field_reports;
create policy "Users can read submitted reports" on public.field_reports
  for select to authenticated using (auth.uid() = submitted_by);

-- Use a server-side admin process or Supabase dashboard to promote users.
-- The role must also be copied into auth.users.app_metadata for JWT role checks.
