const Dashboard = (() => {
	let actions;
	const $ = id => document.getElementById(id);
	const selected = state => state.zones.find(zone => zone.id === state.selectedZoneId) || state.zones[0];
	const levelClass = level => level.toLowerCase();
	function init(callbacks) { actions = callbacks; document.querySelectorAll('.nav-item').forEach(item => item.addEventListener('click', () => actions.switchView(item.dataset.view))); document.querySelectorAll('[data-view-target]').forEach(item => item.addEventListener('click', () => actions.switchView(item.dataset.viewTarget))); $('demo-button').addEventListener('click', runDemo); $('refresh-button').addEventListener('click', () => { actions.applyScenario('Normal'); }); $('zone-details-button').addEventListener('click', () => actions.switchView('intelligence')); $('report-form').addEventListener('submit', submitReport); $('new-report-button').addEventListener('click', () => $('report-observation').focus()); }
	function runDemo() { actions.applyScenario('Normal'); setTimeout(() => actions.applyScenario('Heavy Rain'), 1000); setTimeout(() => actions.applyScenario('Extreme Rain'), 2200); }
	function render(state) { const zone = selected(state); $('last-updated').textContent = state.lastUpdated.toLocaleTimeString('en-IN', { hour12:false }); $('regional-risk').textContent = Math.round(state.zones.reduce((sum,item) => sum + item.score,0) / state.zones.length); $('active-alerts').textContent = String(state.zones.filter(item => item.score >= 55).length).padStart(2,'0'); $('selected-zone-name').textContent = zone.name; $('selected-level').textContent = zone.level.toUpperCase(); $('selected-level').className = `severity-pill ${levelClass(zone.level)}`; $('selected-score').textContent = zone.score; $('score-ring').style.background = `conic-gradient(${zone.level === 'Critical' ? 'var(--red)' : zone.level === 'High' ? 'var(--red)' : 'var(--amber)'} 0 ${zone.score}%, #26343a ${zone.score}% 100%)`; $('selected-confidence').textContent = `${zone.confidence}%`; $('confidence-bar-fill').style.width = `${zone.confidence}%`; $('rainfall-value').textContent = zone.rainfall.toFixed(1); $('moisture-value').textContent = Math.round(zone.moisture); $('temperature-value').textContent = zone.temperature.toFixed(1); $('accumulated-value').textContent = Math.round(zone.accumulated + Math.max(0, state.rainfallBoost * 1.7)); $('risk-explanation').textContent = explanation(zone); $('factor-list').innerHTML = factors(zone).map(item => `<div class="factor"><span>${item.label}</span><strong>${item.value}<b>${item.weight}</b></strong></div>`).join(''); renderZones(state); renderAlerts(state); renderPriority(state); renderReports(state); }
	function explanation(zone) { if (zone.level === 'Critical') return 'Extreme rainfall is pushing soil toward saturation on steep, highly susceptible terrain. Immediate verification is recommended.'; if (zone.level === 'High') return 'Elevated rainfall is saturating already moist soil on steep terrain. Historical events increase baseline susceptibility.'; return 'Current conditions remain below the high-risk threshold, with terrain susceptibility and exposure monitored continuously.'; }
	function factors(zone) { return [{ label:'Rainfall pressure', value:`${Math.round(Math.min(100, zone.rainfall * 1.7))}%`, weight:' +22%' }, { label:'Soil saturation', value:`${Math.round(zone.moisture)}%`, weight:' +16%' }, { label:'Terrain susceptibility', value:`${zone.susceptibility}%`, weight:' +16%' }, { label:'Slope / exposure', value:`${zone.slope}%`, weight:' +12%' }]; }
	function renderZones(state) { $('zone-list').innerHTML = state.zones.map(zone => `<div class="zone-item ${zone.id === state.selectedZoneId ? 'selected' : ''}" data-zone="${zone.id}"><i class="zone-dot ${levelClass(zone.level)}"></i><span class="zone-name">${zone.name}</span><strong class="zone-score">${zone.score}</strong><span class="zone-meta">${zone.level.toUpperCase()} / ${zone.exposure}% EXPOSURE</span></div>`).join(''); document.querySelectorAll('[data-zone]').forEach(item => item.addEventListener('click', () => actions.selectZone(item.dataset.zone))); }
	function renderAlerts(state) { const alerts = state.zones.filter(zone => zone.score >= 55).map(zone => ({ zone, title:zone.level === 'Critical' ? 'Critical threshold exceeded' : 'Rainfall advisory escalated', sub:`${zone.name} / Risk score ${zone.score}`, level:zone.level.toUpperCase(), time:'Now' })); $('alert-list').innerHTML = (alerts.length ? alerts : [{ title:'No active escalation', sub:'All monitored zones remain within baseline thresholds', level:'MONITORING', time:'Now' }]).slice(0,3).map(alert => `<div class="alert-row"><i class="zone-dot ${alert.zone ? levelClass(alert.zone.level) : 'monitoring'}"></i><div><div class="alert-title">${alert.title}</div><div class="alert-sub">${alert.sub}</div></div><span class="alert-time">${alert.time}</span><b class="alert-level">${alert.level}</b></div>`).join(''); $('alert-count').textContent = String(alerts.length).padStart(2,'0'); }
	function renderPriority(state) { const priority = [...state.zones].sort((a,b) => (b.score * .65 + b.exposure * .35) - (a.score * .65 + a.exposure * .35)); $('priority-list').innerHTML = priority.map((zone,index) => `<div class="priority-row"><strong class="priority-number">0${index + 1}</strong><div><div class="priority-title">${zone.name}</div><div class="priority-sub">${zone.exposure}% exposure / ${zone.level}</div></div><span class="alert-time">${Math.round(zone.score * .65 + zone.exposure * .35)} PTS</span></div>`).join(''); }
	function renderIntelligence(state) { $('intelligence-zone-list').innerHTML = state.zones.map(zone => `<div class="intelligence-zone" data-zone-intel="${zone.id}"><i class="zone-dot ${levelClass(zone.level)}"></i><span class="zone-name">${zone.name}</span><span class="severity-pill ${levelClass(zone.level)}">${zone.level}</span><strong class="zone-score">${zone.score}</strong></div>`).join(''); document.querySelectorAll('[data-zone-intel]').forEach(item => item.addEventListener('click', () => { actions.selectZone(item.dataset.zoneIntel); renderIntelligence(AppState); })); const zone = selected(state); $('intelligence-detail').innerHTML = `<div class="panel-kicker">SELECTED ZONE / ${zone.district.toUpperCase()}</div><h2>${zone.name}</h2><p>${explanation(zone)}</p><div class="factor-list">${factors(zone).map(item => `<div class="factor"><span>${item.label}</span><strong>${item.value}<b>${item.weight}</b></strong></div>`).join('')}</div>`; }
	function renderAlertsPage(state) { const priority = [...state.zones].sort((a,b) => b.score - a.score); $('all-alerts').innerHTML = state.zones.map(zone => `<div class="all-alert-row"><i class="zone-dot ${levelClass(zone.level)}"></i><div class="all-alert-main"><strong>${zone.name} / ${zone.level} status</strong><small>Risk ${zone.score} / 100 · ${zone.rainfall.toFixed(1)} mm/hr rainfall · ${zone.moisture}% soil moisture</small></div><span class="severity-pill ${levelClass(zone.level)}">${zone.level.toUpperCase()}</span></div>`).join(''); $('all-priority').innerHTML = priority.map((zone,index) => `<div class="all-alert-row"><strong class="priority-number">0${index+1}</strong><div class="all-alert-main"><strong>${zone.name}</strong><small>${zone.exposure}% exposed assets · ${zone.score} risk score</small></div><span class="alert-level">${zone.level.toUpperCase()}</span></div>`).join(''); }
	function renderReports(state) { $('report-list').innerHTML = state.reports.map(report => `<div class="report-row"><div class="report-main"><strong>${report.location}</strong><small>${report.observation}</small><small>${report.time} · ${report.status}</small></div><span class="severity-pill ${levelClass(report.severity)}">${report.severity.toUpperCase()}</span></div>`).join(''); }
	function submitReport(event) { event.preventDefault(); const location = $('report-location').value; MockAPI.addReport({ location, observation:$('report-observation').value || 'Ground observation submitted for review.', severity:$('report-severity').value, time:'Just now', status:'Under review' }); $('report-form').reset(); renderReports(AppState); actions.showToast('Field report submitted for verification.'); }
	return { init, render, renderIntelligence, renderAlertsPage, renderReports };
})();
