const Dashboard = (() => {
	let actions;
	const $ = id => document.getElementById(id);
	const current = state => state.zones.find(zone => zone.id === state.selectedZoneId) || state.zones[0];
	const levelClass = level => level.toLowerCase();
	function init(callbacks) {
		actions = callbacks;
		document.querySelectorAll('.nav-item').forEach(item => item.addEventListener('click', () => actions.switchView(item.dataset.view)));
		document.querySelectorAll('[data-view-target]').forEach(item => item.addEventListener('click', () => actions.switchView(item.dataset.viewTarget)));
		$('demo-button').addEventListener('click', runDemo); $('refresh-button').addEventListener('click', () => actions.applyScenario('Normal')); $('zone-details-button').addEventListener('click', () => actions.switchView('intelligence')); $('report-form').addEventListener('submit', submitReport); if (!$('report-media')) { const label = document.createElement('label'); label.textContent = 'EVIDENCE PHOTO / VIDEO'; label.innerHTML += '<input id="report-media" type="file" accept="image/*,video/*">'; $('report-form').insertBefore(label, $('report-form').querySelector('.brief-action')); }
	}
	function runDemo() { const button = $('demo-button'); button.disabled = true; button.innerHTML = '<span>●</span> Monitoring escalation'; actions.applyScenario('Normal'); setTimeout(() => actions.applyScenario('Heavy Rain'), 1500); setTimeout(() => actions.applyScenario('Extreme Rain'), 3300); setTimeout(() => { button.disabled = false; button.innerHTML = '<span>▶</span> Run escalation demo'; }, 5100); }
	function animateNumber(element, value, decimals = 0) { const start = Number(element.dataset.value || element.textContent.replace(/[^0-9.-]/g, '')) || 0; const end = Number(value); if (Math.abs(start - end) < .01) return; const began = performance.now(); element.classList.add('changing'); const tick = now => { const progress = Math.min(1, (now - began) / 600); const eased = 1 - Math.pow(1 - progress, 3); element.textContent = decimals ? (start + (end - start) * eased).toFixed(decimals) : Math.round(start + (end - start) * eased); element.dataset.value = end; if (progress < 1) requestAnimationFrame(tick); else element.classList.remove('changing'); }; requestAnimationFrame(tick); }
	function animateGauge(element, score) { const start = Number(element.dataset.score || 0); const began = performance.now(); const tick = now => { const progress = Math.min(1, (now - began) / 700); const eased = 1 - Math.pow(1 - progress, 3); const value = start + (score - start) * eased; element.style.background = `conic-gradient(${score >= 75 ? 'var(--red)' : score >= 55 ? 'var(--orange)' : 'var(--amber)'} 0 ${value}%, #e2ebea ${value}% 100%)`; element.dataset.score = value; if (progress < 1) requestAnimationFrame(tick); }; requestAnimationFrame(tick); }
	function render(state) { const zone = current(state); const previous = (state.previousZones || []).find(item => item.id === zone.id) || zone; const regional = Math.round(state.zones.reduce((sum, item) => sum + item.score, 0) / state.zones.length); $('updated-time').textContent = state.lastUpdated.toLocaleTimeString('en-IN', { hour12:false }); $('clock').textContent = `${state.lastUpdated.toLocaleTimeString('en-IN', { hour12:false })} IST`; animateNumber($('regional-risk'), regional); animateNumber($('active-alerts'), state.alerts.length || state.zones.filter(item => item.score >= 55).length); $('regional-status').textContent = regional >= 75 ? 'CRITICAL' : regional >= 55 ? 'HIGH' : regional >= 35 ? 'ADVISORY' : 'MONITORING'; $('highest-priority').textContent = state.zones.slice().sort((a,b) => b.score - a.score)[0].name.split(' ')[0].toUpperCase(); $('selected-zone-name').textContent = zone.name; $('selected-location').textContent = zone.district; $('selected-level').textContent = zone.level.toUpperCase(); $('selected-level').className = `level-badge ${levelClass(zone.level)}`; animateNumber($('selected-score'), zone.score); animateGauge($('score-ring'), zone.score); $('risk-reading').textContent = `${zone.level.toUpperCase()} RISK`; $('risk-reading').style.color = zone.level === 'Critical' ? 'var(--red)' : zone.level === 'High' ? 'var(--orange)' : 'var(--amber)'; $('selected-confidence').textContent = `${zone.confidence}%`; $('confidence-bar-fill').style.width = `${zone.confidence}%`; animateNumber($('rainfall-value'), zone.rainfall, 1); animateNumber($('moisture-value'), zone.moisture); animateNumber($('temperature-value'), zone.temperature, 1); animateNumber($('accumulated-value'), zone.accumulated + state.rainfallBoost * 1.7); $('forecast-now').textContent = zone.score; $('coordinates').textContent = `${zone.coordinates[0].toFixed(4)}° N, ${zone.coordinates[1].toFixed(4)}° E`; $('risk-explanation').textContent = explanation(zone); $('factor-list').innerHTML = factors(zone).map(item => `<div class="factor"><span>${item.label}</span><strong>${item.value}<b>${item.weight}</b></strong></div>`).join(''); const feed = document.querySelector('.nav-feed'); if (feed) feed.innerHTML = `<i class="dot ${state.backendConnected ? 'green' : 'cyan'}"></i> ${state.backendConnected ? 'Flask API connected' : 'Offline prototype mode'}`; renderChanges(zone, previous); renderExposure(zone); renderZones(state); renderAlerts(state); renderPriority(state); renderReports(state); }
	function explanation(zone) { if (zone.level === 'Critical') return 'Extreme rainfall and near-saturated soil are pushing this steep, susceptible corridor into critical risk.'; if (zone.level === 'High') return 'Heavy rainfall and rising soil saturation are raising risk on highly susceptible terrain.'; return 'Conditions remain below the high-risk threshold while terrain susceptibility and exposure are monitored.'; }
	function factors(zone) { return [{ label:'Rainfall pressure', value:`${Math.min(100, Math.round(zone.rainfall * 1.7))}%`, weight:'+22%' }, { label:'Soil saturation', value:`${Math.round(zone.moisture)}%`, weight:'+16%' }, { label:'Terrain susceptibility', value:`${zone.susceptibility}%`, weight:'+16%' }, { label:'Historical susceptibility', value:`${zone.history}%`, weight:'+8%' }]; }
	function renderChanges(zone, previous) { $('changes-list').innerHTML = [{ label:'Rainfall', value:`${zone.rainfall >= previous.rainfall ? '+' : ''}${(zone.rainfall - previous.rainfall).toFixed(1)}`, note:zone.rainfall > previous.rainfall ? 'increased' : 'stable', tone:zone.rainfall > previous.rainfall ? 'up' : 'steady' }, { label:'Soil', value:`${zone.moisture >= previous.moisture ? '+' : ''}${Math.round(zone.moisture - previous.moisture)}%`, note:zone.moisture > previous.moisture ? 'rising' : 'stable', tone:zone.moisture > previous.moisture ? 'up' : 'steady' }, { label:'Risk', value:`${zone.score >= previous.score ? '+' : ''}${zone.score - previous.score}`, note:`${previous.score} → ${zone.score}`, tone:zone.score > previous.score ? 'risk' : 'steady' }].map(item => `<div class="change-item"><span>${item.label}</span><strong class="${item.tone}">${item.value}</strong><small>${item.note}</small></div>`).join(''); }
	function renderExposure(zone) { const assets = AppState.infrastructure.filter(asset => asset.zone_id === zone.id); $('exposed-population').textContent = assets.length ? `${(assets.reduce((sum, asset) => sum + asset.population_served, 0) / 1000).toFixed(1)}K` : `${(zone.exposure * .15).toFixed(1)}K`; $('roads-at-risk').textContent = String(assets.filter(asset => asset.type === 'road').length || Math.max(1, Math.round(zone.exposure / 28))).padStart(2,'0'); $('villages-count').textContent = String(assets.filter(asset => asset.type === 'village').length || Math.max(2, Math.round(zone.exposure / 12))).padStart(2,'0'); $('infrastructure-count').textContent = String(assets.filter(asset => asset.criticality === 'Critical' || asset.type === 'bridge').length || Math.max(1, Math.round(zone.exposure / 22))).padStart(2,'0'); }
	function renderZones(state) { const list = document.getElementById('zone-list'); if (!list) return; list.innerHTML = state.zones.map(zone => `<div class="zone-row ${zone.id === state.selectedZoneId ? 'selected' : ''}" data-zone="${zone.id}"><i class="dot ${levelClass(zone.level)}"></i><span>${zone.name}</span><strong>${zone.score}</strong></div>`).join(''); document.querySelectorAll('[data-zone]').forEach(item => item.addEventListener('click', () => actions.selectZone(item.dataset.zone))); }
	function renderAlerts(state) { const alerts = state.alerts.length ? state.alerts : state.zones.filter(zone => zone.score >= 55).map(zone => ({ zone_id:zone.id, level:zone.level, title:`${zone.level} risk detected`, reason:zone.name, risk_score:zone.score })); $('alert-count').textContent = String(alerts.length).padStart(2,'0'); $('alert-list').innerHTML = (alerts.length ? alerts : [{ title:'No active escalation', level:'Monitoring', risk_score:0 }]).slice(0,3).map(alert => `<div class="alert-row"><i class="dot ${levelClass(alert.level)}"></i><div><strong>${alert.title}</strong><small>${alert.reason || 'All zones remain below threshold'}${alert.risk_score ? ` · Risk ${alert.risk_score}` : ''}</small></div><b>${alert.risk_score ? alert.level.toUpperCase() : 'CLEAR'}</b></div>`).join(''); }
	function renderPriority(state) { const priority = [...state.zones].sort((a,b) => b.score * .65 + b.exposure * .35 - (a.score * .65 + a.exposure * .35)); $('priority-list').innerHTML = priority.slice(0,3).map((zone,index) => `<div class="priority-row"><strong>0${index + 1}</strong><div><b>${zone.name}</b><small>${zone.level.toUpperCase()} · ${zone.exposure}% exposure</small></div><em>${zone.level === 'Critical' || zone.level === 'High' ? 'VERIFY NOW' : 'MONITOR'}</em></div>`).join(''); }
	function renderIntelligence(state) { $('intelligence-zone-list').innerHTML = state.zones.map(zone => `<div class="intelligence-zone" data-zone-intel="${zone.id}"><i class="dot ${levelClass(zone.level)}"></i><span>${zone.name}</span><b>${zone.score}</b></div>`).join(''); document.querySelectorAll('[data-zone-intel]').forEach(item => item.addEventListener('click', () => actions.selectZone(item.dataset.zoneIntel))); const zone = current(state); $('intelligence-detail').innerHTML = `<p class="kicker">SELECTED ZONE / ${zone.district.toUpperCase()}</p><h2>${zone.name}</h2><p>${explanation(zone)}</p><div class="factor-list">${factors(zone).map(item => `<div class="factor"><span>${item.label}</span><strong>${item.value}<b>${item.weight}</b></strong></div>`).join('')}</div>`; }
	function renderAlertsPage(state) { $('all-alerts').innerHTML = state.zones.map(zone => `<div class="all-alert-row"><i class="dot ${levelClass(zone.level)}"></i><div><strong>${zone.name}</strong><small>Risk ${zone.score} · ${zone.rainfall.toFixed(1)} mm/hr · ${Math.round(zone.moisture)}% soil moisture</small></div><b>${zone.level.toUpperCase()}</b></div>`).join(''); $('all-priority').innerHTML = state.zones.slice().sort((a,b) => b.score - a.score).map((zone,index) => `<div class="all-alert-row"><strong>0${index+1}</strong><div><strong>${zone.name}</strong><small>${zone.exposure}% exposure</small></div><b>${zone.level === 'Critical' || zone.level === 'High' ? 'IMMEDIATE VERIFICATION' : 'MONITOR'}</b></div>`).join(''); }
	function renderReports(state) { $('report-list').innerHTML = state.reports.map(report => `<div class="report-row"><div><strong>${report.location}</strong><small>${report.observation}</small><small>${report.time} · ${report.status}</small></div><b>${report.severity.toUpperCase()}</b></div>`).join(''); }
	async function submitReport(event) { event.preventDefault(); const media = $('report-media').files[0]; const report = { zone_id:AppState.selectedZoneId, location:$('report-location').value, observation:$('report-observation').value || 'Ground observation submitted for review.', severity:$('report-severity').value, timestamp:new Date().toISOString(), status:'Under review', media_type:media ? media.type : null, media_name:media ? media.name : null }; if (navigator.geolocation) await new Promise(resolve => navigator.geolocation.getCurrentPosition(position => { report.latitude = position.coords.latitude; report.longitude = position.coords.longitude; report.accuracy_m = position.coords.accuracy; resolve(); }, resolve, { enableHighAccuracy:true, timeout:5000, maximumAge:60000 })); await actions.submitReport(report); $('report-form').reset(); renderReports(AppState); actions.showToast('Field report entered into the verification queue.'); }
	return { init, render, renderIntelligence, renderAlertsPage, renderReports };
})();