const MapView = (() => {
	let map; let zoneLayer; let selectedMarker; let activeMode = 'risk'; let selectZone;
	const layers = {};
	function init(selectCallback) {
		selectZone = selectCallback;
		const element = document.getElementById('risk-map');
		if (window.L) {
			map = L.map(element, { zoomControl:false, attributionControl:true, minZoom:5, maxZoom:18, zoomSnap:.25, zoomDelta:.5, scrollWheelZoom:true, wheelDebounceTime:20, wheelPxPerZoomLevel:90, zoomAnimation:true, fadeAnimation:true, markerZoomAnimation:true, touchZoom:true, inertia:true, worldCopyJump:false }).setView([26.85, 93.7], 6);
			L.control.zoom({ position:'bottomright' }).addTo(map);
			layers.terrain = L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', { maxZoom:17, maxNativeZoom:17, tileSize:256, updateWhenZooming:false, updateWhenIdle:true, keepBuffer:4, attribution:'OpenTopoMap' });
			layers.satellite = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', { maxZoom:19, maxNativeZoom:19, tileSize:256, updateWhenZooming:false, updateWhenIdle:true, keepBuffer:4, attribution:'Esri World Imagery' });
			layers.roads = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom:19, maxNativeZoom:19, opacity:.42, updateWhenZooming:false, updateWhenIdle:true, keepBuffer:4, attribution:'OpenStreetMap' });
			layers.satellite.addTo(map); layers.roads.addTo(map); zoneLayer = L.layerGroup().addTo(map);
		}
		document.querySelectorAll('.map-control').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.map-control').forEach(item => item.classList.remove('active')); button.classList.add('active'); activeMode = button.dataset.mapMode; renderMode(activeMode); }));
		window.addEventListener('resize', resize);
		document.addEventListener('bhusanket:authenticated', resize);
	}
	function resize() { if (!map) return; requestAnimationFrame(() => { map.invalidateSize({ animate:false, pan:false }); map.setView(map.getCenter(), map.getZoom(), { animate:false }); }); }
	function color(zone) { return zone.level === 'Critical' ? '#d34438' : zone.level === 'High' ? '#d36c36' : zone.level === 'Advisory' ? '#d5a03b' : '#4d9d69'; }
	function render(state) { const selected = state.zones.find(zone => zone.id === state.selectedZoneId) || state.zones[0]; document.getElementById('coordinates').textContent = `${selected.coordinates[0].toFixed(4)}° N, ${selected.coordinates[1].toFixed(4)}° E`; renderLocationSwitcher(state); if (!map) return; zoneLayer.clearLayers(); state.zones.forEach(zone => { const source = [zone.coordinates[0] + .045, zone.coordinates[1] - .055]; const isSelected = zone.id === state.selectedZoneId; const point = L.circleMarker(zone.coordinates, { radius:isSelected ? 10 : 6, color:color(zone), weight:isSelected ? 3 : 2, fillColor:color(zone), fillOpacity:isSelected ? .9 : .68, bubblingMouseEvents:false }); point.bindTooltip(`<strong>${zone.name}</strong><br>${zone.district}<br><b>${zone.score} / 100 · ${zone.level}</b><br><small>Click to monitor this zone</small>`, { direction:'top', className:'map-tooltip', sticky:true }); point.on('click', () => selectZone(zone.id)); point.addTo(zoneLayer); const impactRadius = 2500 + zone.score * 65; const impact = L.circle(zone.coordinates, { radius:impactRadius, color:color(zone), weight:isSelected ? 2 : 1, dashArray:isSelected ? '6 5' : '3 6', fillColor:color(zone), fillOpacity:isSelected ? .13 : .055, interactive:isSelected }); impact.bindTooltip(`<strong>Probable impact area</strong><br>${zone.name}<br>Estimated radius: ${(impactRadius / 1000).toFixed(1)} km<br><b>Assistance may be needed here</b>`, { className:'map-tooltip', sticky:true }); impact.addTo(zoneLayer); if (isSelected) { const sourceMarker = L.circleMarker(source, { radius:8, color:'#a92f28', weight:2, fillColor:'#e34236', fillOpacity:.95 }); sourceMarker.bindTooltip(`<strong>Potential landslide source</strong><br>Steep terrain instability detected<br>Flow direction shown by arrow`, { direction:'top', className:'map-tooltip', sticky:true }); sourceMarker.addTo(zoneLayer); const flow = L.polyline([source, zone.coordinates], { color:'#d64d3f', weight:2, dashArray:'7 6', opacity:.9 }); flow.bindTooltip('<strong>Probable slide path</strong><br>Material may travel toward the exposed area', { className:'map-tooltip' }); flow.addTo(zoneLayer); const arrow = L.marker([zone.coordinates[0] + .017, zone.coordinates[1] - .021], { icon:L.divIcon({ className:'slide-arrow', html:'➜', iconSize:[20,20], iconAnchor:[10,10] }), interactive:false }); arrow.addTo(zoneLayer); } }); if (activeMode === 'rainfall') state.zones.forEach(zone => L.circle(zone.coordinates, { radius:zone.rainfall * 330, color:'#3e82a1', weight:1, fillColor:'#4e9ab9', fillOpacity:.2, interactive:false }).addTo(zoneLayer)); if (activeMode === 'roads') layers.roads.setOpacity(.9); if (activeMode !== 'roads') layers.roads.setOpacity(.35); if (selected.id !== map._selectedZone) { map.flyTo(selected.coordinates, map.getZoom() < 8 ? 10 : map.getZoom(), { duration:.85, easeLinearity:.15 }); map._selectedZone = selected.id; } }
	function renderLocationSwitcher(state) { const switcher = document.getElementById('map-location-switcher'); if (!switcher) return; switcher.innerHTML = state.zones.map(zone => `<button class="map-place ${zone.id === state.selectedZoneId ? 'active' : ''}" data-map-zone="${zone.id}"><i class="place-dot" style="background:${color(zone)}"></i><span>${zone.name}</span><b>${zone.score}</b></button>`).join(''); switcher.querySelectorAll('[data-map-zone]').forEach(button => button.addEventListener('click', () => selectZone(button.dataset.mapZone))); }
	function renderMode(mode) { const label = document.getElementById('active-layer'); if (label) label.textContent = `${mode.toUpperCase()} OVERLAY`; if (!map) return; if (mode === 'terrain') { map.removeLayer(layers.satellite); layers.terrain.addTo(map); } else { map.removeLayer(layers.terrain); layers.satellite.addTo(map); } }
	return { init, render };
})();